### ISSUE TITLE
Should the payer DFSP send a PUT /thirdpartyRequests/transaction/{id} back to the PISP before issuing the Quote?

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/pisp#56]
According to the FSPIOP-API Spec for transaction requests, the payer DFSP send  a `PUT /transactionRequest/{id}` request to the Payee DFSP before issuing a quote.

Ref: [641-service-details](https://docs.mojaloop.io/mojaloop-specification/documents/API%20Definition%20v1.0.html#641-service-details)

In our current PISP designs, we don't have this request, but instead rely soley on the `POST /authorization` to proceed, or `PUT /thirdpartyRequests/transaction/{id}/error` to fail the thirdparty transaction.

**Question: Do we need to have a `PUT /thirdpartyRequests/transaction/{id}` from the PayerDFSP -> PISP ?**

For sake of consistency between the api patterns, I think we should, but I'm very open to other thoughts.

**Comment by elnyry-sam-k** [comment]
Having a have a `PUT /thirdpartyRequests/transaction/{id}` sounds good Lewis, as we also look to standardize the API.

**Comment by lewisdaly** [comment]
Yeah I think so - we initially overlooked this, but the more we dig into the error scenarios, the more it seems necessary.
