### ISSUE TITLE
[Change Request] - Allow limited broadcast messages with multiple `FSPIOP-Destination` header values

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/pisp#79]
>**WARNING: Controversial idea ahead**

## Background

In 2 places in the proposed Account Linking API flows in the 3rd party API, we have cases where two participants need to be updated simultaneously.

1. in [`POST /consents`](https://github.com/mojaloop/pisp/blob/master/docs/linking/README.md#15-grant-consent), when a DFSP creates the pending `Consent` object, it needs to update both the PISP and auth-service
> Note: for a DFSP nominating to run their own Auth-Service, this is not an issue, as we can assume they update the auth-service out of band
2. In [`PUT /consents/{id}`](http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/mojaloop/pisp/master/docs/linking/5b-credential-registration-2.puml&cache=no), the auth-service must update both the DFSP and PISP of the finalized `Consent` object

In the past, we had the idea of using a pub/sub messaging system as was previously proposed for the final transaction notification. Since that proposal was rejected, we no longer have a generic idea for how a participant (i.e. the PISP) can subscribe to _arbitrary updates_ to a resource.

Indeed, that was a lofty goal, and since the current working proposal for the transaction notification is not as generic, we need a new method for updating multiple participants from a single API call.

## Proposal

**Allow participants to address messages to multiple participants by setting multiple values for the `FSPIOP-Destination` Header.**

[RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) allows for comma separated values for HTTP headers.

The switch (in this case `thirdparty-api-adapter` service) could receive 1 inbound request, recognize more than value for the `FSPIOP-Destination`, and then forward that inbound request to a participant for each value contained in the `FSPIOP-Destination`.

For example:
1. DFSP sends a `POST /consents` request, with a `FSPIOP-Destination` header value of `pispA,central-auth`
2. The `thirdparty-api-adapter` sees this request, and recognizes multiple destinations for this request
3. The `thirdparty-api-adapter` performs 2 URL lookups: One for `pispA` and another for `central-auth`
4. The `thirdparty-api-adapter` forwards the `POST /consents` request to each of the participants 

### Constraints
> These  constraints ensure that this feature is not abused by a participant. Please suggest others or modifications to these rules

1. The values of the `FSPIOP-Destination` header should not contain duplicates participantIds, and if it does contain duplicate ids, they are ignored.
> e.g. a value of `pispA,central-auth,central-auth` would be treated as `pispA,central-auth`

2. To protect the Switch from DDOS attacks, there should be only 1 value allowed per participant type, in the types of `PISP, DFSP, and Auth-Service`. This means that a Participant cannot send a message to more than 1 DFSP or more than 1 PISP.

### Questions:

1. How do we handle downstream failures and callbacks to the original request sender?

**Comment by jgeewax** [comment]
> How do we handle downstream failures and callbacks to the original request sender?

How do we handle them now? This is equivalent to making two requests, one after the other, with the only difference between the two being that the destination header is different. An error response might be routed back to the sender (of which there is always one), and the sender can decide whether the error response merits any further communication, right?

**Comment by lewisdaly** [comment]
Currently, we handle downstream failures using the `PUT .../error` callback to the originator.

e.g. 
1. DFSPA calls `POST /quotes`
2. switch fails to find endpoint for the `FSPIOP-Destination`
3. switch calls `PUT /quotes/{id}/error` back to DFSPA

There is a 1-1 relationship between the initial call and the potential error callback for that call.

In our broadcast message proposal, this gets a little trickier, and we likely would need a special error code to handle these cases. For example, where a DFSPA sends a message with 2 values for `FSPIOP-Destination`, that results in 2 messages, **A** and **B** the following are possible:

1. **A** and **B** succeed
1. **A** succeeds and **B** fails
1. **A** fails and **B** succeeds
1. Both **A** and **B** fail

I think we need to make some heuristics for how the switch will send error callbacks:
1. Given a single broadcast message, the switch will send _at most one_ error callback to the `FSPIOP-Source`
1. If no downstream messages fail, no error callback will be sent.
1. If any downstream message fails, then the error callback is sent. The contents of the error callback will describe the details of which downstream messages failed.
1. The originator of the message must interpret the error message to retry messages to specific participants

**Comment by lewisdaly** [comment]
This was shut down pretty robustly. Let's not make changes to the message forwarding logic.
